version: '3'

services:

  sbv_prod_db:
    container_name: sbv_prod_db
    hostname: sbv_prod_db
    image: mongo
    restart: always
    volumes:
      - sbv_prod_db:/data/db
    networks:
      - iatric
    ports:
      - 27017/tcp
    environment:
      MONGO_INITDB_DATABASE: sbv_prod_db
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  sbv_prod:
    container_name: sbv_prod
    hostname: sbv_prod
    networks:
      - iatric
    image: docker.iatric.com/sbv:${VERSION}-alpine
    restart: unless-stopped
    depends_on:
      - sbv_prod_db
    ports:
      - 43401:443/tcp
    volumes:
      - /home/iatric/certificates:/app/certificates
      - /home/iatric/apps/sbv_prod/watch:/app/watch
      - /home/iatric/apps/sbv_prod/error:/app/error
      - /home/iatric/apps/sbv_prod/staticFiles:/app/staticFiles
    env_file:
      - /home/iatric/global.env
    environment:
      APPLICATION_API: https://sbv_prod/api
      APPLICATION_API_CLIENT: https://${SERVER_HOSTNAME}:43401/api
      APPLICATION_NAME: Smartboard Vision [PROD]
      APPLICATION_URL: https://${SERVER_HOSTNAME}:43401/
      APPLICATION_UUID: 589e3ffe-42ef-4717-81f2-22c5c4533429
      APPLICATIONMANAGER_API: https://fastlane_prod/api
      APPLICATIONMANAGER_API_CLIENT: https://${SERVER_HOSTNAME}:43400/api
      DB: mongodb://sbv_prod_db/sbv_prod
      ICONNECT_SITECODE: ${ICONNECT_SITECODE}
      MONGO_USER: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_USER_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      NODE_ENV: production
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      PORT: 443
      X_AUTH_REFRESH_TOKEN_EXPIRATION: 480
      X_AUTH_REFRESH_TOKEN_SECRET: ${X_AUTH_TOKEN_SECRET}
      X_AUTH_TOKEN_EXPIRATION: 15
      X_AUTH_TOKEN_SECRET: ${X_AUTH_TOKEN_SECRET}

volumes:
  sbv_prod_db: {}

networks:
  iatric:
    external: true