version: "3"
services:
  watchtower:
    container_name: watchtower
    hostname: watchtower
    image: containrrr/watchtower
    restart: always
    networks:
      - iatric
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  iatric:
    external: true