version: '3'

services:

  fastlane_prod_db:
    container_name: fastlane_prod_db
    hostname: fastlane_prod_db
    image: mysql/mysql-server:8.0
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: 'fastlane'
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
      MYSQL_DATABASE: 'fastlane_prod'
    ports:
      - 3306
    networks:
      - iatric
    volumes:
      - /home/iatric/databases/mysql/fastlane_prod:/var/lib/mysql

  fastlane_prod:
    container_name: fastlane_prod
    hostname: fastlane_prod
    networks:
      - iatric
    image: docker.iatric.com/fastlane:${VERSION}-alpine
    restart: unless-stopped
    ports:
      - 43400:443/tcp
    volumes:
      - /home/iatric/certificates:/app/certificates
      - /home/iatric/apps/fastlane_prod/uploads:/app/uploads
    environment:
      APPLICATION_API: https://fastlane_prod/api
      APPLICATION_API_CLIENT: https://${SERVER_HOSTNAME}:43400/api
      APPLICATION_NAME: Fastlane [PROD]
      APPLICATION_URL: https://${SERVER_HOSTNAME}:43400/
      APPLICATION_UUID: ef38f527-7e47-4680-a978-cd4c51789a52
      APPLICATIONMANAGER_API: https://fastlane_prod/api
      APPLICATIONMANAGER_API_CLIENT: https://${SERVER_HOSTNAME}:43400/api
      DB_DIALECT: mysql
      DB_HOSTNAME: fastlane_prod_db
      DB_LOGGING: 0
      DB_NAME: fastlane_prod
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_PORT: 3306
      DB_USERNAME: fastlane
      ICONNECT_SITECODE: ${ICONNECT_SITECODE}
      NODE_ENV: production
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      PORT: 443
      X_AUTH_REFRESH_TOKEN_EXPIRATION: 480
      X_AUTH_REFRESH_TOKEN_SECRET: ${X_AUTH_TOKEN_SECRET}
      X_AUTH_TOKEN_EXPIRATION: 15
      X_AUTH_TOKEN_SECRET: ${X_AUTH_TOKEN_SECRET}

networks:
  iatric:
    external: true