version: '3.7'

x-fastlane-app: &fastlane-app fastlane_{$ENVIRONMENT}_app
x-fastlane-db: &fastlane-db fastlane_{$ENVIRONMENT}_db
x-mysql-user: &mysql-user ${MYSQL_USER}
x-mysql-pass: &mysql-pass ${MYSQL_PASSWORD}

# ENVIRONMENT
# VERSION

# SITE_CODE
# SERVER_HOSTNAME
# TOKEN_SECRET

# MYSQL_USER
# MYSQL_PASS

services:

  db:
    container_name: *fastlane-db
    hostname: *fastlane-db
    image: mysql/mysql-server:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password --lower-case-table-names=1 --innodb-buffer-pool-size=1073741824 --innodb-log-file-size=268435456 --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=O_DIRECT
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: *mysql-user
      MYSQL_PASSWORD: *mysql-pass
      MYSQL_DATABASE: *fastlane-app
    ports:
      - 3306
    networks:
      - iatric
    volumes:
      - fastlane_${ENVIRONMENT}_db:/var/lib/mysql

  app:
    container_name: *fastlane-app
    hostname: *fastlane-app
    networks:
      - iatric
    image: docker.iatric.com/fastlane:${VERSION}-alpine
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - ${PORT}:443/tcp
    volumes:
      - /home/iatric/certificates:/app/certificates
      - /home/iatric/apps/fastlane_${ENVIRONMENT}/uploads:/app/uploads
    environment:
      APPLICATION_API: https://fastlane_${ENVIRONMENT}/api
      APPLICATION_API_CLIENT: https://${SERVER_HOSTNAME}:${PORT}/api
      APPLICATION_NAME: Fastlane [${ENVIRONMENT}]
      APPLICATION_URL: https://${SERVER_HOSTNAME}:${PORT}/
      APPLICATION_UUID: ef38f527-7e47-4680-a978-cd4c51789a52
      APPLICATIONMANAGER_API: https://fastlane_${ENVIRONMENT}/api
      APPLICATIONMANAGER_API_CLIENT: https://${SERVER_HOSTNAME}:${PORT}/api
      DB_DIALECT: mysql
      DB_HOSTNAME: *fastlane-db
      DB_LOGGING: 0
      DB_NAME: *fastlane-app
      DB_PASSWORD: *mysql-pass
      DB_PORT: 3306
      DB_USERNAME: *mysql-user
      ICONNECT_SITECODE: ${SITE_CODE}
      NODE_ENV: production
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      PORT: 443
      X_AUTH_REFRESH_TOKEN_EXPIRATION: 480
      X_AUTH_REFRESH_TOKEN_SECRET: ${TOKEN_SECRET}
      X_AUTH_TOKEN_EXPIRATION: 15
      X_AUTH_TOKEN_SECRET: ${TOKEN_SECRET}

volumes:
  fastlane_${ENVIRONMENT}_db: {}

networks:
  iatric:
    external: true