version: "3"
services:
  nginx_proxy_manager:
    container_name: nginx_proxy_manager
    hostname: nginx_proxy_manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    networks:
      - iatric
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      DISABLE_IPV6: 'true'
    volumes:
      - /home/iatric/nginx/data:/data
      - /home/iatric/letsencrypt:/etc/letsencrypt
  
networks:
  iatric:
    external: true  